apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx-dep
  labels:
    app: xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxx
  template:
    metadata:
      labels:
        app: xxx
    spec:
      containers:
      - name: xxx
        image: 192.168.152.106:8443/cpuhog:v1.0
